pub mod camera;
pub mod color;
mod constants;
mod fibonacci_spiral;
pub mod frame_buffer;
pub mod hit;
pub mod lights;
pub mod line_drawer;
pub mod materials;
pub mod objects;
mod photon;
mod primitives;
pub mod ray;
pub mod scene;
